[project]
name = "typed-rubicon-objc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typed-rubicon-objc.IOBluetooth",
    "typed-rubicon-objc.Foundation",
    "typing-extensions>=4.15.0",
]

[dependency-groups]
lint = [
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "ruff>=0.15.0",
    "ty>=0.0.15",
]
test = [
    "pytest>=9.0.2",
]

[tool.uv.sources]
"typed-rubicon-objc.IOBluetooth" = { workspace = true }
"typed-rubicon-objc.Foundation" = { workspace = true }

[tool.uv.workspace]
members = [
    "frameworks/*",
]

[tool.mypy]
mypy_path = "typings"
packages = "typed_rubicon_objc.Foundation,typed_rubicon_objc.IOBluetooth,tests"
namespace_packages = true

[tool.pyright]
typeCheckingMode = "strict"

[tool.ty.environment]
extra-paths = ["typings"]
python = ".venv"
