import ctypes
from typing import TYPE_CHECKING, NewType, TypeAlias, overload

from rubicon.objc.api import ObjCProtocol
from rubicon.objc.runtime import SEL, objc_id
from typed_rubicon_objc.Foundation import (
    NSUUID,
    NSArray,
    NSData,
    NSDate,
    NSDictionary,
    NSNumber,
    NSObject,
    NSString,
)
from typing_extensions import Buffer, Self

IOBluetooth: ctypes.CDLL

IOReturn: TypeAlias = int

if TYPE_CHECKING:
    BluetoothRFCOMMChannelID: TypeAlias = int
    BluetoothRFCOMMMTU: TypeAlias = int
    IOBluetoothObjectID: TypeAlias = int
    BluetoothClassOfDevice: TypeAlias = int
    BluetoothConnectionHandle: TypeAlias = int
    BluetoothDeviceClassMajor: TypeAlias = int
    BluetoothDeviceClassMinor: TypeAlias = int
    BluetoothServiceClassMajor: TypeAlias = int
    BluetoothClockOffset: TypeAlias = int
    BluetoothHCIEncryptionMode: TypeAlias = int
    BluetoothLinkType: TypeAlias = int
    BluetoothPageScanMode: TypeAlias = int
    BluetoothPageScanPeriodMode: TypeAlias = int
    BluetoothPageScanRepetitionMode: TypeAlias = int
    BluetoothHCIPageTimeout: TypeAlias = int
    BluetoothHCIRSSIValue: TypeAlias = int

class IOBluetoothRFCOMMChannelDelegate(ObjCProtocol): ...

kDefaultPageTimeout: BluetoothHCIPageTimeout

class BluetoothDeviceAddress:
    def __init__(self, data: bytes) -> None: ...
    def data(self) -> bytes: ...

class IOBluetoothDevice(IOBluetoothObject):
    @classmethod
    def deviceWithAddress(
        cls, address: BluetoothDeviceAddress, /
    ) -> IOBluetoothDevice: ...
    @classmethod
    def deviceWithAddressString(cls, address: NSString, /) -> IOBluetoothDevice: ...
    @property
    def addressString(self) -> NSString: ...
    @property
    def classOfDevice(self) -> BluetoothClassOfDevice: ...
    @property
    def connectionHandle(self) -> BluetoothConnectionHandle: ...
    def deviceClassMajor(self) -> BluetoothDeviceClassMajor: ...
    @property
    def deviceClassMinor(self) -> BluetoothDeviceClassMinor: ...
    @property
    def handsFreeAudioGateway(self) -> bool: ...
    @property
    def handsFreeDevice(self) -> bool: ...
    @property
    def lastNameUpdate(self) -> NSData: ...
    @property
    def name(self) -> NSString: ...
    def nameOrAddress(self) -> NSString: ...
    @property
    def serviceClassMajor(self) -> BluetoothServiceClassMajor: ...
    @property
    def services(self) -> NSArray[IOBluetoothSDPServiceRecord] | None: ...
    def addToFavorites(self) -> IOReturn: ...
    def closeConnection(self) -> IOReturn: ...
    def getAddress(self) -> BluetoothDeviceAddress: ...
    def getClockOffset(self) -> BluetoothClockOffset: ...
    def getEncryptionMode(self) -> BluetoothHCIEncryptionMode: ...
    def getLastInquiryUpdate(self) -> NSDate: ...
    def getLastServicesUpdate(self) -> NSDate: ...
    def getLinkType(self) -> BluetoothLinkType: ...
    def getPageScanMode(self) -> BluetoothPageScanMode: ...
    def getPageScanPeriodMode(self) -> BluetoothPageScanPeriodMode: ...
    def getPageScanRepetitionMode(self) -> BluetoothPageScanRepetitionMode: ...
    def getServiceRecordForUUID(
        self, sdpUUID: IOBluetoothSDPUUID, /
    ) -> IOBluetoothSDPServiceRecord | None: ...
    def handsFreeAudioGatewayServiceRecord(self) -> IOBluetoothSDPServiceRecord: ...
    def handsFreeDeviceServiceRecord(self) -> IOBluetoothSDPServiceRecord: ...
    def isConnected(self) -> bool: ...
    def isFavorite(self) -> bool: ...
    def isIncoming(self) -> bool: ...
    def isPaired(self) -> bool: ...
    @overload
    def openConnection(self) -> IOReturn: ...
    @overload
    def openConnection(self, target: NSObject, /) -> IOReturn: ...
    @overload
    def openConnection(
        self,
        target: NSObject,
        /,
        *,
        withPageTimeout: BluetoothHCIPageTimeout,
        authenticationRequired: bool,
    ) -> IOReturn: ...
    @overload
    def openL2CAPChannelAsync(
        self,
        newChannel: IOBluetoothL2CAPChannel,
        /,
        *,
        withPSM: BluetoothL2CAPPSM,
        delegate: NSObject,
    ) -> IOReturn: ...
    @overload
    def openL2CAPChannelAsync(
        self,
        newChannel: IOBluetoothL2CAPChannel,
        /,
        *,
        withPSM: BluetoothL2CAPPSM,
        withConfiguration: NSDictionary[NSString, NSObject],
        delegate: NSObject,
    ) -> IOReturn: ...
    @overload
    def openL2CAPChannelSync(
        self,
        newChannel: IOBluetoothL2CAPChannel,
        /,
        *,
        withPSM: BluetoothL2CAPPSM,
        delegate: NSObject,
    ) -> IOReturn: ...
    @overload
    def openL2CAPChannelSync(
        self,
        newChannel: IOBluetoothL2CAPChannel,
        /,
        *,
        withPSM: BluetoothL2CAPPSM,
        withConfiguration: NSDictionary[NSString, NSObject],
        delegate: NSObject,
    ) -> IOReturn: ...
    def openRFCOMMChannelAsync(
        self,
        rfcommChannel: ctypes._Pointer[objc_id] | ctypes._CArgObject,  # pyright: ignore[reportPrivateUsage]
        /,
        *,
        withChannelID: BluetoothRFCOMMChannelID,
        delegate: NSObject,
    ) -> IOReturn: ...
    def openRFCOMMChannelSync(
        self,
        rfcommChannel: ctypes._Pointer[objc_id] | ctypes._CArgObject,  # pyright: ignore[reportPrivateUsage]
        /,
        *,
        withChannelID: BluetoothRFCOMMChannelID,
        delegate: NSObject,
    ) -> IOReturn: ...
    @overload
    def performSDPQuery(self, /, target: NSObject) -> IOReturn: ...
    @overload
    def performSDPQuery(
        self, target: NSObject, /, *, uuids: NSArray[NSUUID]
    ) -> IOReturn: ...
    def rawRSSI(self) -> BluetoothHCIRSSIValue: ...
    def recentAccessDate(self) -> NSDate: ...
    def registerForDisconnectNotification(
        self, observer: NSObject, /, *, selector: SEL
    ) -> IOBluetoothUserNotification: ...
    @overload
    def remoteNameRequest(self, /, target: NSObject) -> IOReturn: ...
    @overload
    def remoteNameRequest(
        self, target: NSObject, /, *, withPageTimeoutValue: BluetoothHCIPageTimeout
    ) -> IOReturn: ...
    def removeFromFavorites(self) -> IOReturn: ...
    def requestAuthentication(self) -> IOReturn: ...
    def RSSI(self) -> BluetoothHCIRSSIValue: ...
    def sendL2CAPEchoRequest(self, data: bytes, /, *, length: int) -> IOReturn: ...
    def setSupervisionTimeout_(self, timeout: int, /) -> IOReturn: ...
    @classmethod
    def favoriteDevices(cls) -> NSArray[IOBluetoothDevice] | None: ...
    @classmethod
    def pairedDevices(cls) -> NSArray[IOBluetoothDevice] | None: ...
    @classmethod
    def recentDevices(cls, numDevices: int, /) -> NSArray[IOBluetoothDevice] | None: ...
    @classmethod
    def registerForConnectNotifications(
        cls, observer: NSObject, /, *, selector: SEL
    ) -> IOBluetoothUserNotification: ...

class IOBluetoothDeviceInquiry(NSObject):
    def initWithDelegate(self, delegate: NSObject) -> Self: ...
    def delegate(self) -> NSObject: ...
    def setDelegate(self, delegate: NSObject, /) -> None: ...
    def inquiryLength(self) -> int: ...
    def setInquiryLength(self, inquiryLength: int, /) -> None: ...
    def searchType(self) -> IOBluetoothDeviceSearchTypes: ...
    def setSearchType(self, searchType: IOBluetoothDeviceSearchTypes, /) -> None: ...
    def updateNewDeviceNames(self) -> bool: ...
    def setUpdateNewDeviceNames(self, update: bool, /) -> None: ...
    def clearFoundDevices(self) -> None: ...
    def foundDevices(self) -> NSArray[IOBluetoothDevice]: ...
    def setSearchCriteria(
        self,
        serviceClassMajor: BluetoothServiceClassMajor,
        /,
        *,
        majorDeviceClass: BluetoothDeviceClassMajor,
        minorDeviceClass: BluetoothDeviceClassMinor,
    ) -> None: ...
    def start(self) -> IOReturn: ...
    def stop(self) -> IOReturn: ...
    @classmethod
    def inquiryWithDelegate_(cls, delegate: NSObject) -> IOBluetoothDeviceInquiry: ...

IOBluetoothDeviceSearchTypes = NewType(
    "IOBluetoothDeviceSearchTypes", IOBluetoothDeviceSearchTypeBits
)
IOBluetoothDeviceSearchTypeBits = NewType("IOBluetoothDeviceSearchTypeBits", int)

kIOBluetoothDeviceSearchClassic: IOBluetoothDeviceSearchTypeBits
kIOBluetoothDeviceSearchLE: IOBluetoothDeviceSearchTypeBits

class BluetoothRFCOMMLineStatus: ...

BluetoothRFCOMMLineStatusFramingError: BluetoothRFCOMMLineStatus
BluetoothRFCOMMLineStatusNoError: BluetoothRFCOMMLineStatus
BluetoothRFCOMMLineStatusOverrunError: BluetoothRFCOMMLineStatus
BluetoothRFCOMMLineStatusParityError: BluetoothRFCOMMLineStatus

class BluetoothRFCOMMParityType: ...

kBluetoothRFCOMMParityTypeEvenParity: BluetoothRFCOMMParityType
kBluetoothRFCOMMParityTypeMaxParity: BluetoothRFCOMMParityType
kBluetoothRFCOMMParityTypeNoParity: BluetoothRFCOMMParityType
kBluetoothRFCOMMParityTypeOddParity: BluetoothRFCOMMParityType

class IOBluetoothUserNotificationChannelDirection: ...

kIOBluetoothUserNotificationChannelDirectionAny: (
    IOBluetoothUserNotificationChannelDirection
)
kIOBluetoothUserNotificationChannelDirectionIncoming: (
    IOBluetoothUserNotificationChannelDirection
)
kIOBluetoothUserNotificationChannelDirectionOutgoing: (
    IOBluetoothUserNotificationChannelDirection
)

class IOBluetoothObject(NSObject): ...

class IOBluetoothUserNotification(NSObject):
    def unregister(self) -> None: ...

class IOBluetoothRFCOMMChannel(IOBluetoothObject):
    def closeChannel(self) -> int: ...
    def delegate(self) -> NSObject: ...
    def getDevice(self) -> IOBluetoothDevice: ...
    def getChannelID(self) -> BluetoothRFCOMMChannelID: ...
    def getMTU(self) -> BluetoothRFCOMMMTU: ...
    def getObjectID(self) -> IOBluetoothObjectID: ...
    def getRFCOMMChannelRef(self) -> IOBluetoothRFCOMMChannelRef: ...
    def isIncoming(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def isTransmissionPaused(self) -> bool: ...
    def registerForChannelCloseNotification(
        self, observer: NSObject, /, *, selector: SEL
    ) -> IOBluetoothUserNotification: ...
    def sendRemoteLineStatus(
        self, lineStatus: BluetoothRFCOMMLineStatus, /
    ) -> IOReturn: ...
    def setDelegate(self, delegate: NSObject, /) -> IOReturn: ...
    def setSerialParameters(
        self,
        speed: int,
        /,
        *,
        dataBits: int,
        parity: BluetoothRFCOMMParityType,
        stopBits: int,
    ) -> IOReturn: ...
    def writeAsync(self, data: bytes, /, *, length: int, refcon: int) -> IOReturn: ...
    def writeSync(self, data: bytes, /, *, length: int) -> IOReturn: ...
    @classmethod
    @overload
    def registerForChannelOpenNotifications(
        cls, object: NSObject, /, *, selector: SEL
    ) -> IOBluetoothUserNotification: ...
    @classmethod
    @overload
    def registerForChannelOpenNotifications(
        cls,
        object: NSObject,
        /,
        *,
        selector: SEL,
        withChannelID: BluetoothRFCOMMChannelID,
        direction: IOBluetoothUserNotificationChannelDirection,
    ) -> IOBluetoothUserNotification: ...
    @classmethod
    def withObjectID(
        cls, objectID: IOBluetoothObjectID, /
    ) -> IOBluetoothRFCOMMChannel: ...
    @classmethod
    def withRFCOMMChannelRef_(
        cls, rfcommChannelRef: IOBluetoothRFCOMMChannelRef, /
    ) -> IOBluetoothRFCOMMChannel: ...

class IOBluetoothRFCOMMChannelRef: ...

class IOBluetoothSDPServiceRecord(NSObject):
    @classmethod
    def initWithServiceDictionary(
        cls,
        serviceDict: NSDictionary[NSNumber | int, IOBluetoothSDPDataElement],
        /,
        *,
        device: IOBluetoothDevice,
    ) -> IOBluetoothSDPServiceRecord: ...
    @property
    def attributes(self) -> NSDictionary[NSNumber | int, IOBluetoothSDPDataElement]: ...
    @property
    def device(self) -> IOBluetoothDevice: ...
    @property
    def sortedAttributes(self) -> NSArray[IOBluetoothSDPServiceAttribute]: ...
    def getAttributeDataElement(
        self, attributeID: BluetoothSDPServiceAttributeID, /
    ) -> IOBluetoothSDPDataElement: ...
    def getServiceRecordHandle(
        self,
        serviceRecordHandle: ctypes._CArgObject,  # pyright: ignore[reportPrivateUsage]
        /,
    ) -> IOReturn: ...
    def getL2CAPPSM(
        self,
        outPSM: ctypes._Pointer[ctypes.c_uint16] | ctypes._CArgObject,  # pyright: ignore[reportPrivateUsage]
        /,
    ) -> IOReturn: ...
    def getRFCOMMChannelID(
        self,
        rfcommChannelID: ctypes._Pointer[ctypes.c_uint8] | ctypes._CArgObject,  # pyright: ignore[reportPrivateUsage]
        /,
    ) -> IOReturn: ...
    def getServiceName(self) -> NSString: ...
    def hasServiceFromArray(self, array: NSArray[IOBluetoothSDPUUID], /) -> bool: ...
    def matchesSearchArray(
        self, searchArray: NSArray[NSArray[IOBluetoothSDPUUID]], /
    ) -> bool: ...
    def matchesUUID16(self, uuid16: int, /) -> bool: ...
    def matchesUUIDArray(self, uuidArray: NSArray[IOBluetoothSDPUUID], /) -> bool: ...
    def removeServiceRecord(self) -> IOReturn: ...

BluetoothSDPServiceAttributeID = NewType("BluetoothSDPServiceAttributeID", int)
BluetoothSDPServiceRecordHandle = NewType("BluetoothSDPServiceRecordHandle", int)
BluetoothL2CAPPSM = NewType("BluetoothL2CAPPSM", int)

class IOBluetoothSDPUUID(NSData):
    @classmethod
    def uuidWithBytes(cls, bytes: Buffer, /, *, length: int) -> Self: ...
    @classmethod
    def uuidWithData(cls, data: NSData | Buffer, /) -> Self: ...
    @classmethod
    def uuidWithUUID16(cls, uuid16: int, /) -> Self: ...
    @classmethod
    def uuidWithUUID32(cls, uuid32: int, /) -> Self: ...
    def getUUIDWithLength(self, length: int, /) -> bytes: ...
    def isEqualToUUID(self, uuid: IOBluetoothSDPUUID, /) -> bool: ...
    @classmethod
    def uuid16(cls, uuid16: BluetoothSDPUUID16, /) -> Self: ...
    @classmethod
    def uuid32(cls, uuid32: BluetoothSDPUUID32, /) -> Self: ...

BluetoothSDPUUID16 = NewType("BluetoothSDPUUID16", int)
BluetoothSDPUUID32 = NewType("BluetoothSDPUUID32", int)

class IOBluetoothL2CAPChannel(IOBluetoothObject): ...
class IOBluetoothSDPDataElement(NSObject): ...
class IOBluetoothSDPServiceAttribute(NSObject): ...
