# Note: Foundation types (NS*) from rubicon.objc.api and rubicon.objc.types are
# intentionally redefined here in order to be able to include more methods that
# reference other types not available in rubicon.objc package.

# pyright: reportPrivateUsage=false

import ctypes
import typing
from abc import ABCMeta
from collections.abc import Iterator, Mapping, Sequence
from typing import Any, Self, TypeVar

from rubicon.objc.api import ObjCProtocol

__all__ = [
    "NSObject",
    "NSNumber",
    "NSDecimalNumber",
    "NSString",
    "NSData",
    "NSArray",
    "NSMutableArray",
    "NSDictionary",
    "NSMutableDictionary",
]

class _NSObjectMeta(type):
    def __new__(cls, protocols: list[ObjCProtocol] = []) -> Any: ...

class NSObject(typing.Protocol, metaclass=_NSObjectMeta):
    def __init__(self, id: ctypes.c_void_p) -> None: ...
    @classmethod
    def alloc(cls) -> Self: ...
    @classmethod
    def allocWithZone(cls, zone: None, /) -> Self: ...
    def init(self) -> Self: ...
    @property
    def copy(self) -> Self: ...
    @classmethod
    def copyWithZone(cls, zone: None, /) -> Self: ...
    @property
    def mutableCopy(self) -> Self: ...
    @classmethod
    def mutableCopyWithZone(cls, zone: None, /) -> Self: ...
    def dealloc(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    @classmethod
    def instancesRespondToSelector(cls, selector: bytes, /) -> bool: ...
    @classmethod
    def conformsToProtocol(cls, protocol: ObjCProtocol, /) -> bool: ...
    def methodForSelector(self, selector: bytes, /) -> ctypes._CFunctionType: ...
    @property
    def ptr(self) -> ctypes._Pointer[Self]: ...

class NSNumber(NSObject): ...
class NSDecimalNumber(NSObject): ...
class NSString(NSObject): ...
class NSData(NSObject): ...

_T = TypeVar("_T")

class _NSArrayMeta(_NSObjectMeta, ABCMeta): ...
class NSArray(NSObject, Sequence[_T], metaclass=_NSArrayMeta): ...

NSMutableArray = ...

_TKey = TypeVar("_TKey")
_TValue = TypeVar("_TValue")

class _NSDictionaryMeta(_NSObjectMeta, ABCMeta): ...

class NSDictionary(NSObject, Mapping[_TKey, _TValue], metaclass=_NSDictionaryMeta):
    def allKeys(self) -> NSArray[_TKey]: ...
    def allValues(self) -> NSArray[_TValue]: ...
    def objectForKey_(self, key: _TKey) -> _TValue: ...
    def __getitem__(self, key: _TKey) -> _TValue: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_TKey]: ...

NSMutableDictionary = ...
